### ISSUE TITLE
PhpStorm not respecting some settings when editorconfig plugin installed

### ISSUE THREAD

**Issue by antonymous** [editorconfig/editorconfig-jetbrains#21]
When installed, plugin somehow prevents PhpStorm from remembering editor appearance settings "Show whitespaces" and "Show line numbers"; ~~and also from opening files as Windows-1251 (they are opened as UTF-8) despite file encodings is set to "Windows-1251" at the project level~~ (UPDATE: not relevant, uninstalled plugin and still occasionally having the issue).
Everything is back to normal when I uninstall the plugin.
Ubuntu 13.04 x86_64, Java v.7 & v.8-EA, PhpStorm is latest EA-version, build 131-205.

**Comment by kenkouot** [comment]
Same as #14

**Comment by bellkev** [comment]
Closed as duplicate of #14
