### ISSUE TITLE
Show line numbers is always set to false when editorconfig plugin enabled

### ISSUE THREAD

**Issue by jkbrzt** [editorconfig/editorconfig-jetbrains#24]
The `Preferences > Editor > Appearance > Show Line Numbers` option, when checked, doesn't survive editor restart when the  editorconfig plugin is enabled.

Tested on PyCharm 3.0.1.

**Comment by fdeweger** [comment]
Same here with phpstorm version 7.0, using ubuntu 12.04

**Comment by bellkev** [comment]
This is a dup of #14. Please see there for additional comments
