### ISSUE TITLE
Already disposed Exception in PhpStorm 7

### ISSUE THREAD

**Issue by noodny** [editorconfig/editorconfig-jetbrains#26]
Exception with message: "Already disposed: Project (Disposed) food: Already disposed: Project (Disposed) food" occurs on every focus in/out of the window, and on project opening. Tested in PhpStorm 7.0 (Build #PS-131.374) and JRE 1.7.0_10

**Comment by fpigerre** [comment]
This issue also seems to occur in IntelliJ IDEA (#32)
