### ISSUE TITLE
Allow setup continuation indent size through editorconfig

### ISSUE THREAD

**Issue by maksimr** [editorconfig/editorconfig-jetbrains#41]
Sometimes continuation indent size different from indent size.

Will be cool allow setup `continuation_indent_size` in **editorconfig**:

```
[**.js]
indent_size: 2
continuation_indent_size: 4
```

if continuation indent size [not present then we can setup it how indent size](https://github.com/editorconfig/editorconfig-jetbrains/blob/master/src/org/editorconfig/configmanagement/CodeStyleManager.java#L153).

Thanks!

**Comment by os97673** [comment]
The plugin is supposed to support  properties which are supported editorconfig, the property is not supported and thus I'd suggest to file ticket in editorconfig/editorconfig instead.

**Comment by xuhdev** [comment]
User customized property is not prohibited by the editorconfig core libraries, but you need to have some more flexibility in the plugin, which is similar to the [Hook Mechanism in the Vim plugin](https://github.com/editorconfig/editorconfig-vim/blob/8a757cd8f85d1da5de798e6f373776cb45d1fee5/doc/editorconfig.txt#L143). Maybe, it's better to modify it as a feature request to support something like that?

**Comment by maksimr** [comment]
@xuhdev Thanks!
I think vim plugin is great example!

**Comment by rayshan** [comment]
+1

**Comment by denofevil** [comment]
continuation_indent_size added in https://github.com/JetBrains/intellij-community/commit/570f7cba223e02032e810731d44d8b26a7258dfb. Hooks will be added sometime later
