### ISSUE TITLE
Provide visual indication

### ISSUE THREAD

**Issue by rayshan** [editorconfig/editorconfig-jetbrains#43]
It's hard to tell if the plugin is working or if a new `.editorconfig` file was detected. Would be nice to have a pop up that can be disabled.

**Comment by rayshan** [comment]
Another thought - would be nice to have a custom icon similar to what other plugins offer.
![screen shot 2014-07-23 at 9 46 32 pm](https://cloud.githubusercontent.com/assets/3760840/3853214/6521eb06-1ebf-11e4-9bd2-1ff71c3a7ac2.png)

**Comment by denofevil** [comment]
This repository is now obsolete, IntelliJ based products will feature editorconfig support. Please track this issue [here](http://youtrack.jetbrains.com/issue/IDEA-129859)

**Comment by rayshan** [comment]
@denofevil thanks
