### ISSUE TITLE
Plugin doesn't appear to work with comma separated list of matchers

### ISSUE THREAD

**Issue by jblack10101** [editorconfig/editorconfig-jetbrains#45]
I have several rules that I'd like to apply to several different types of files, but the plugin doesn't seem to be picking up the values correctly when I use commas:

```
[{*.java,*.groovy,*.js,*.css,*.json,*.xml,*.gradle,*.jsp,*.html}]
```

If I cut this down to just [_] or [_.groovy], the rules work fine.  But once I modify it to be [{_.groovy,_.java}], it no longer works.

There's a note that this is only supported in EditorConfig Core 0.11.0 and later, so is this plugin using an older version of the core?

**Comment by denofevil** [comment]
As far as I understand from the website, {} is supposed to match list of strings and no regular expressions are supposed to be expanded in there. This is somewhat proved by test data: https://github.com/editorconfig/editorconfig-core-test/blob/master/glob/braces.in#L6. Also that link suggests workaround to your problem, you can use [*.{java,groovy,js,css,json,xml,gradle,jsp,html}] instead.

@treyhunner, what do you think? Do we need to expand regular expressions inside {}? If not, I think it would make sense to say that explicitly.

**Comment by jblack10101** [comment]
Ah alright, my fault.  Yea, 

```
[*.{java,groovy}]
```

works.  Thanks!

**Comment by treyhunner** [comment]
@denofevil this is discussed in editorconfig/editorconfig#81.  The nested-braces branch in editorconfig-core-tests can be used to test for this.

**Comment by denofevil** [comment]
Ok, I see, thanks a lot. Java core was reimplemented using Python one as example, so currently it doesn't support this.

**Comment by denofevil** [comment]
Fixed with editorconfig/editorconfig-core-java@27d3a2171e9cf537d0594bf9aad69b0855e788d0
