### ISSUE TITLE
WebStorm 9 provides native support for EditorConfig

### ISSUE THREAD

**Issue by JamesMGreene** [editorconfig/editorconfig-jetbrains#49]
FYI, JetBrains WebStorm 9 (["What's New?"](http://www.jetbrains.com/webstorm/whatsnew/index.html?mkt_tok=3RkMMJWWfF9wsRoks6vIZKXonjHpfsX56uwpWKe1hIkz2EFye%2BLIHETpodcMSMZlN6%2BTFAwTG5toziV8R7THKs1xzNEQWhDm)) now provides native support for EditorConfig.

I assume it will be coming to the other JetBrains editors soon.

You may want to add a note to the README, though any users of older versions would still need to utilize this plugin.

**Comment by uwolfer** [comment]
It is included by default in IntellIJ 14 (at least in ultimate).

**Comment by denofevil** [comment]
Replaced readme with new repository and issue tracker links, thank you
