### ISSUE TITLE
Only seems to enforce editorconfig settings when editing, not when saving

### ISSUE THREAD

**Issue by LegalizeAdulthood** [editorconfig/editorconfig-jetbrains#50]
For instance, if I have the policy set to say that the final newline should always be applied, and I open a file that doesn't have this and select save, the file remains unchanged.

**Comment by stoeffel** [comment]
+1

**Comment by smazurov** [comment]
:+1:

**Comment by peterfoeng** [comment]
Same issue here :(

**Comment by xuhdev** [comment]
It seems that JetBrains has integrated this plugin into the IDE itself. Maybe you should report to their bug tracker to make them aware of the problem?

**Comment by denofevil** [comment]
Now it's tracked as [WEB-14368](https://youtrack.jetbrains.com/issue/WEB-14368)
