### ISSUE TITLE
Reformat whole project to editorconfig rules?

### ISSUE THREAD

**Issue by dziamid** [editorconfig/editorconfig-jetbrains#54]
Is it possilbe to instantly apply editorconfig rules to all project files (or maybe a scope based selection of files)?

**Comment by denofevil** [comment]
Which IDE and what version are you using?

**Comment by denofevil** [comment]
Due to internal platform changes this feature will be available only in IDEA Ultimate 14+, WebStorm 9+, RubyMine 7+, PhpStorm 8.0.2+, PyCharm 4+, AppCode 3.1+. To apply rules simply use reformat code action. Updated plugin for IDEs that don't bundle it yet will be available soon
