### ISSUE TITLE
Remove popup

### ISSUE THREAD

**Issue by adam-lynch** [editorconfig/editorconfig-jetbrains#55]
I find this popup to be very annoying:

![image](https://cloud.githubusercontent.com/assets/1427241/5167102/99af1154-73ed-11e4-85ed-c41269d8836f.png)

Sometimes it even shows it for each file, so I could see like 6 popups appear at once.

I expect it to be working, it should only pop up when there's a problem (like if I give a bad value for a field, etc.)

I'm using IntelliJ Ultimate 14 on Windows 8.1.

**Comment by denofevil** [comment]
Fixed with JetBrains/intellij-community@507aaad51ea9248ad0d71f18dd1f32bd73d199b2

**Comment by adam-lynch** [comment]
Thanks. When will this change be out there? How do I get it? From the JetBrains plugin repo / editorconfig.org?

**Comment by denofevil** [comment]
It will be available in IDEA Ultimate 14.0.2 or 14.0.3 automatically. In the meanwhile you can just disable notification in Settings | Appearance & Behavior | Notifications

**Comment by adam-lynch** [comment]
Thanks :+1:
