### ISSUE TITLE
Pattern mismatch error

### ISSUE THREAD

**Issue by HA3IK** [editorconfig/editorconfig-jetbrains#59]
> OS: Win10
> IDE: PhpStorm

Hello,
When I set properties:
```
[*]
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false
```
...all files like `.bowerrc`, `.gitignore`, `.editorconfig` doesn't remove whitespace characters, too.
**And in general, the plugin works very badly in real time**

**P.S:** In other editions I did not have any problems.

**Comment by xuhdev** [comment]
Please use the new [issue tracker](https://youtrack.jetbrains.com/issues?q=tag%3A+EditorConfig).
