### ISSUE TITLE
Editorconfig IntelliJ plugin take  precedence over google-java-format IntelliJ plugin ? 

### ISSUE THREAD

**Issue by BruceZu** [editorconfig/editorconfig-jetbrains#61]
Hi guys,
Just want to confirm if Editorconfig IntelliJ plugin take precedence over google-java-format IntelliJ plugin?
Thank you!
Bruce

**Comment by xuhdev** [comment]
JetBrains has taken over the project to their own code repository (as the README has indicated). You would probably have to ask at https://youtrack.jetbrains.com/issues?q=tag:%20EditorConfig
