### ISSUE TITLE
Host on Github

### ISSUE THREAD

**Issue by treyhunner** [editorconfig/editorconfig-jetbrains#9]
You might consider hosting your releases on Github (see [this blog post](https://github.com/blog/1547-release-your-software)).  You should be using version tags anyways and releases are easy to add to them on Github.

This would be an alternative to the external link in your README file.

**Comment by bellkev** [comment]
Oh, cool. Somehow I thought I read somewhere that Github wouldn't host binaries, which is why I threw up that other site. I had already been tagging the releases so far, so I just pushed them to Github and added the zip files.
